# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-01 22:16
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20180401_2203'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('new_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
