# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20180407_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='is_rate',
            new_name='is_vote',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/img/default_pic.png', upload_to='static/img/'),
        ),
    ]
